# -----------------------------------------------------------------------------
# Site Settings
# -----------------------------------------------------------------------------

name: Jerome Pansanel
email: jerome.pansanel@iphc.cnrs.fr

footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a>.
# last_updated: true

url: https://www.pansanel.net
baseurl:  # the subpath of your site, e.g. /blog/
description: >
  This web page presents the engineering and research activities of Jerome
  Pansanel. It covers several scientific fields, like  big data, cloud and grid
  computing, bioinformatics, cheminformatics and artificial intelligence.
last_updated: 07-02-2021

# -----------------------------------------------------------------------------
# Social Integration
# -----------------------------------------------------------------------------
github_username: Pansanel
linkedin_username: jeromepansanel
twitter_username: pansanel
orcid_id: https://orcid.org/0000-0002-7067-5009
research_gate_profile: https://www.researchgate.net/profile/Jerome_Pansanel
contact_note: Feel free to contact me via e-mail.

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
# blog_name: al-folio
# blog_description: a simple whitespace theme for academics

# # Pagination
# paginate: 4
# permalink: /blog/:year/:title/
# paginate_path: /blog/page:num/

# text:
#   pagination:
#     newer: 'Newer'
#     older: 'Older'

# # Comments
# disqus_shortname: al-folio # put your disqus shortname

# # Optional features
# show_social_icons:  false
# enable_anchorjs:    false
# enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: page
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 10

# -----------------------------------------------------------------------------
# Jekyll Settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
# highlighter: pygments

# Includes
include: ['_pages']

# Plugins
plugins:
  - jekyll-paginate
  - jekyll/scholar
  - jemoji

# Jekyll-Scholar
scholar:
  last_name: Stretcu
  style: apa
  locale: en
  sort_by: year
  order: descending
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: publication
  reference_tagname: div

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.7.1"
anchorjs_version: "3.2.2"
